navikt/omsorgspengesoknad-prosessering

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1Metrics.kt, src/test/kotlin/no/nav/helse/SøknadsformatTest.kt
https://jira.adeo.no/browse/BR-110
=> Dev br 110 nye metrics

.github/workflows/build-and-deploy.yml, nais/dev-fss.yml, nais/prod-fss.yml
Migrer til nais-deploy action og simplifiserer ci/cd fil.
Fjerner jobb for trigging av workflow via deployment.
Flytter miljøvariabler til globale miljøvariabler i workflow.
=> Migrer til nais deploy action

src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt, src/main/resources/handlebars/soknad.hbs, src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt
Dersom bruker ikke har lastet opp legeerklæring så skal det komme opp et punkt i PDF som sier det.
=> Dev legeerklæring pdf ved ingen vedlegg

nais/alerterator.yml
Øker tiden for "Applikasjon nede" alert fra 2min til 10min.
Øker tiden for varsling av streams fra 1min, til 20 min.
=> Endrer tiden for alarmer

src/main/kotlin/no/nav/helse/joark/JoarkGateway.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/JournalforingsStream.kt
Før har det blitt logget "Journalpost blir opprettet uten navn på søker.". Sendte inn søknad nå, logger ikke den warningen lenger
=> Legger til navn på requesten til k9-joark

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt, src/main/resources/handlebars/soknad.hbs, src/test/kotlin/no/nav/helse/OmsorgspengesoknadProsesseringTest.kt, src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt, src/test/kotlin/no/nav/helse/SøknadsformatTest.kt
Refaktorerer Arbeidssituasjon til Enum.
Dytter også opp dusseldrofKtor, Gradle og Kotlin jvm.
=> Refaktorerer Arbeidssituasjon til Enum

nais/prod-fss.json
Beholder mulighet for å filtrere på datoer, hvis feilen gjentar seg.
=> Setter kafka-autooffset-reset til none i prod. 

src/main/kotlin/no/nav/helse/OmsorgspengesoknadProsessering.kt, src/main/kotlin/no/nav/helse/dokument/Søknadsformat.kt, src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/Topics.kt, src/main/resources/handlebars/soknad.hbs, src/test/kotlin/no/nav/helse/OmsorgspengesoknadProsesseringTest.kt, src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt, src/test/kotlin/no/nav/helse/SøknadsformatTest.kt
Oppdaterer tester
Oppdaterer pdf
=> Rydde bort utgåtte felter

.github/workflows/build-and-deploy.yml, src/main/kotlin/no/nav/helse/prosessering/v1/PreprosseseringV1Service.kt
Endrer dokumentbeskrivelse.
Oppdaterer actions.
Closes #62
Closes #63
=> Fiks tekst og oppdatere actions

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Oppdaterer shadow og gradle wrapper. Closes #66
Oppdaterer kotlin jvm. Closes #65
Oppdaterer handlebars. Closes #67
=> Oppdaterer avhengigheter

.github/workflows/build-and-deploy.yml, build.gradle.kts, src/main/kotlin/no/nav/helse/prosessering/Metadata.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/Topology.kt, src/test/kotlin/no/nav/helse/KafkaWrapper.kt
Fjerner requestId fra Metadata.
Closes #69
Closes #70
=> Oppdaterer avhengigheter.

src/main/resources/application.conf
Preautorisert for k9-joark og k9-dokument  
https://github.com/navikt/aad-iac/pull/501
=> Bruke verdier direkte fra AzureAD

nais/dev-fss.json, nais/naiserator.yml, nais/prod-fss.json, src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt, src/main/resources/application.conf
Fjerner også logging av PDF generering.
=> Fjerner integrasjon til vault og plukker opp secret fra kubernetes.

build.gradle.kts, src/main/kotlin/no/nav/helse/Configuration.kt, src/main/kotlin/no/nav/helse/OmsorgspengesoknadProsessering.kt, src/test/kotlin/no/nav/helse/OmsorgspengesoknadProsesseringTest.kt
Fjerner deprecated annotation
Closes #78
=> Oppdatere pakker.

nais/dev-fss.json, nais/naiserator.yml, nais/prod-fss.json, src/main/kotlin/no/nav/helse/Configuration.kt, src/main/kotlin/no/nav/helse/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/helse/prosessering/v1/K9Beskjed.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/CleanupStream.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/JournalforingsStream.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/PreprosseseringStream.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/Topics.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/Topology.kt, src/main/resources/application.conf, src/test/kotlin/no/nav/helse/KafkaWrapper.kt, src/test/kotlin/no/nav/helse/OmsorgspengesoknadProsesseringTest.kt, src/test/kotlin/no/nav/helse/TestConfiguration.kt, src/test/kotlin/no/nav/helse/TestUtils.kt
Refaktorerer Topics, TopicsEntry og SerDes for å matche andre applikasjoner. 
Sender K9Beskjed videre som k9-dittnav-varsel plukker opp.
Refaktorerer tester.
=> Migrere til Aiven

build.gradle.kts, src/main/kotlin/no/nav/helse/Configuration.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
=> Oppdatere openhtmltopdfVersion og fiks deprecated metode.

nais/prod-fss.json, nais/topics.yml, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/Topics.kt
Setter offset.reset til none.
Fjerner mottatt-v2 topic.
Annoterer at alt skal slettes når ressursen slettes.
=> Opprydding etter migrering. 

.github/workflows/apply-alerts.yml, .github/workflows/build-and-deploy.yml, .github/workflows/deploy-kafka.yml, .github/workflows/sny.yml, build.gradle.kts
Oppdaterer dusseldorfKtorVersion, handlebars, K9-Format og actions/checkout.
Samkjører Java versjon.
Bruker JUnit5 for test.
Fjerner ubrukt biblioteker.
* Closes #96
* Closes #98
=> Oppdaterer pakker

.github/dependabot.yml, .github/workflows/build-and-deploy.yml, build.gradle.kts
=> Oppdatere pakker

build.gradle.kts, src/test/kotlin/no/nav/helse/SøknadUtils.kt
=> Oppdaterer k9-format og dusseldorf-ktor

.github/workflows/build-and-deploy.yml, build.gradle.kts
=> Oppdaterer setup-java og k9Format.

src/main/kotlin/no/nav/helse/dokument/K9MellomlagringGateway.kt, src/main/kotlin/no/nav/helse/dokument/K9MellomlagringService.kt, src/main/kotlin/no/nav/helse/joark/JoarkGateway.kt, src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprosesseringV1Service.kt, src/main/kotlin/no/nav/helse/prosessering/v1/PreprosessertMeldingV1.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/CleanupStream.kt, src/main/kotlin/no/nav/helse/prosessering/v1/asynkron/JournalforingsStream.kt, src/test/kotlin/no/nav/helse/OmsorgspengesoknadProsesseringTest.kt, src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt, src/test/kotlin/no/nav/helse/SøknadUtils.kt
Legger til støtte for å motta vedleggId i stedet for url fra api.
=> Journalføre med dokumentId.

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
=> Håndterer at samværsavtale kan være null fra API.

.github/workflows/apply-alerts.yml, .github/workflows/build-and-deploy.yml, .github/workflows/deploy-kafka.yml, .github/workflows/snyk.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
* Closes #151
* Closes #150
* Closes #149
* Closes #148
=> Oppdaterer k9-format og actions.

.github/workflows/build-and-deploy.yml, Dockerfile, build.gradle.kts
=> Oppdatere til distroless java 17 og pakker.

Dockerfile, nais/dev-gcp.json, nais/naiserator.yml, nais/prod-gcp.json
Snyk UI kjenner til imaget, og den er uten kjente sårbarheter pr.dd.
- Bruker service discovery url mot k9-mellomlagring.
=> Bytter baseimage til Amazon Corretto 17-Alpine.
